### ISSUE TITLE
Can't select text

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-front#23]
We can't select text in the UI, presumably because of how we capture mouse events. In most of the interface this isn't important, but a user may want to copy metadata from the sidebar, text from the login/about etc. The sidebar is probably the main issue here.

(tested with chromium and firefox)

**Comment by kamil4** [comment]
I had a look at this while improving multiselect. It turns out that multiselect support itself does *not* cause this. Rather, it's `user-select: none;` in CSS.

As an experiment, I commented out all `user-select` instances. Unsurprisingly, text selection started working, but it also became clear why `user-select: none;` was used. Without it, when doing area-select, text in overlays in albums and photos gets selected, which looks ugly.

Still, I do think that we could be more selective about it. Right now it's disabled globally but we could reenable it in selected places (such as the sidebar -- there's already code and CSS to do it, but it's broken). Or we could enable it globally and disable it in selected places (I guess basically just overlays and dividers in albums and album views?). What do you think?
