### ISSUE TITLE
Refreshing (F5) an album or photo from within the search results fails with 422

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee-front#328]
### Detailed description of the problem

Since https://github.com/LycheeOrg/Lychee-front/pull/306 by @kamil4 Lychee properly supports the back button for albums and photos which are opened within the search results. This was made possible by "faking" the album ID as `#search/<search term>`. If one opens an album from within the search results, the whole URL becomes `#search/<search term>/<actual album ID>`. When one refreshes the page (e.g. press Strg+F5), one gets an `422 Unprocessable Entity` error.

### Steps to reproduce the issue

 1. Open Lychee
 2. Run a search which yields an album
 3. Open that album from within the search results
 4. Press Strg+F5

_Background:_ The JS `init` function false tries to run the HTTP query `api/getAlbum` with the fake album ID `#search/<search term>` which is not a proper album ID and hence the backend returns a 422 response. Instead, the frontend should identify the URL as a search URL and re-run the search. Currently, the frontend is not well prepared if a user directly opens a search URL.

### Output of the diagnostics (Settings => Diagnostics)

not relevant here

### Browser and system

not relevant here

**Comment by kamil4** [comment]
I can't reproduce this with albums, because for albums the URL I see is simply `#<actual album ID>` (as expected). Hitting a reload will result in the fake search parent ID being lost, but I don't think there's any way to fix that, since we don't embed the parent ID in the URL.

I can definitely reproduce this for photos though. I'll see what I can do about fixing that. In principle we do reload search results when coming back from an album, so there's code to do that in at least one place, but I guess not everywhere that it's needed...

**Comment by ildyria** [comment]
Fixed.
